add stackoverflow basic service
itmo-cet-sem/franky pull request #30
Opened 2019-04-18 21:08 UTC by ValeriaShestakova

2019-04-20 14:02 UTC, tcibinan requested changes
Thanks for you work!

Please check a few comments below.

2019-04-20 14:02 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        self._rest_endpoint = 'https://api.stackexchange.com/2.2'
It looks good to me to add `rest_endpoint` constructor parameter with a default value `https://api.stackexchange.com/2.2`.

2019-04-20 14:02 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +    def user(self, user_name):
Missing method return type parameter `UserData`.

2019-04-20 14:02 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +            raise Exception('Username is not unique!')
Btw, I don't think we have to fail in the case. Probably, we should log a warning and return one of the user's data.

2019-04-20 14:02 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        user_id = response_data['items'][0]['user_id']
As I see the code will fail with `ValueError` or ` IndexError` if a user is not found. Probably, we should handle the case and throw an exception with a proper error message. Some custom error type f.e. `StackoverflowServiceException` will be of help.

2019-04-20 14:02 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        payload['site'] = self._service_name
It is not a good practise to mutate function parameter values. The better approach will be to create a copy of a dictionary and then mutate it.

2019-04-21 20:47 UTC, tcibinan requested changes

2019-04-21 20:47 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        elif len(data) == 1:
I suppose we should handle the `len(data) == 1` case the same way we handle `len(data) > 1`.

2019-04-21 20:47 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        full_payload = payload
It is not a copying of the dictionary. The `a = b` means that you copy not the object but its pointer to another variable. What I meant in the previous review was the following:
```
full_payload = dict(payload)
```
The operation above really *copies* the object rather then its pointer.

2019-04-22 21:03 UTC, tcibinan approved these changes

2019-04-23 01:55 UTC, dyadyaJora approved these changes

2019-04-25 19:46 UTC, merged