[Frontend] Github basic api process
itmo-cet-sem/franky pull request #32
Opened 2019-04-20 13:15 UTC by dyadyaJora

Implement #31 
+ Only redux actions for api calls to server
+ Components clearfixes
+ Beautifull views on next PRs

2019-04-20 14:05 UTC, tcibinan requested changes

2019-04-20 14:05 UTC, tcibinan commented on frontend/src/containers/Observe/Observe.js
> +        <h3>Try iy now!</h3>
Just a typo.

2019-04-21 08:47 UTC, tcibinan requested changes
Please configure codacy validations for javascript - expected number of quotes in strings and etc.

2019-04-23 02:51 UTC, dyadyaJora commented
> Please configure codacy validations for javascript - expected number of quotes in strings and etc.

done

2019-04-23 08:41 UTC, tcibinan approved these changes

2019-04-24 22:31 UTC, merged