add tags weight for stackoverflow
itmo-cet-sem/franky pull request #43
Opened 2019-04-30 20:25 UTC by ValeriaShestakova

2019-04-30 22:23 UTC, tcibinan requested changes

2019-04-30 22:23 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +            sum_tags = reduce(lambda a, b: a + b, [tag['count'] for tag in response_data])
You can replace lambda with `operator.add` from standard library.

2019-04-30 22:23 UTC, tcibinan commented on backend/franky/service/stackoverflow/stackoverflow.py
> +        except TypeError:
What is the case when `TypeError` is thrown? 

Btw if you catch the error please log it using `logging` package rather then ignoring it.

2019-05-04 13:10 UTC, tcibinan approved these changes

2019-05-04 15:54 UTC, DostonAkhmedov approved these changes

2019-05-05 08:10 UTC, dyadyaJora approved these changes

2019-05-05 08:59 UTC, merged